In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("cars-used.csv")

In [3]:
df

model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0        A1  2017  12500       Manual    15735   Petrol  150  55.4         1.4
1        A6  2016  16500    Automatic    36203   Diesel   20  64.2         2.0
2        A1  2016  11000       Manual    29946   Petrol   30  55.4         1.4
3        A4  2017  16800    Automatic    25952   Diesel  145  67.3         2.0
4        A3  2019  17300       Manual     1998   Petrol  145  49.6         1.0
...     ...   ...    ...          ...      ...      ...  ...   ...         ...
10663    A3  2020  16999       Manual     4018   Petrol  145  49.6         1.0
10664    A3  2020  16999       Manual     1978   Petrol  150  49.6         1.0
10665    A3  2020  17199       Manual      609   Petrol  150  49.6         1.0
10666    Q3  2017  19499    Automatic     8646   Petrol  150  47.9         1.4
10667    Q3  2016  15999       Manual    11855   Petrol  150  47.9         1.4

[10668 rows x 9 columns]

In [4]:
df.columns

Index(['model', 'year', 'price', 'transmission', 'mileage', 'fuelType', 'tax',
       'mpg', 'engineSize'],
      dtype='object')

In [5]:
df.isna().sum()

model           0
year            0
price           0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      0
dtype: int64

In [6]:
df['model'].unique()

array([' A1', ' A6', ' A4', ' A3', ' Q3', ' Q5', ' A5', ' S4', ' Q2',
       ' A7', ' TT', ' Q7', ' RS6', ' RS3', ' A8', ' Q8', ' RS4', ' RS5',
       ' R8', ' SQ5', ' S8', ' SQ7', ' S3', ' S5', ' A2', ' RS7'],
      dtype=object)

In [7]:
df['transmission'].unique()

array(['Manual', 'Automatic', 'Semi-Auto'], dtype=object)

In [8]:
df['fuelType'].unique()

array(['Petrol', 'Diesel', 'Hybrid'], dtype=object)

In [9]:
from sklearn.preprocessing import OneHotEncoder

In [11]:
encoder=OneHotEncoder()
encoder.fit(df)

OneHotEncoder()

In [13]:
encoder.categories_

[array([' A1', ' A2', ' A3', ' A4', ' A5', ' A6', ' A7', ' A8', ' Q2',
        ' Q3', ' Q5', ' Q7', ' Q8', ' R8', ' RS3', ' RS4', ' RS5', ' RS6',
        ' RS7', ' S3', ' S4', ' S5', ' S8', ' SQ5', ' SQ7', ' TT'],
       dtype=object),
 array([1997, 1998, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
        2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020]),
 array([  1490,   1699,   1975, ..., 137500, 137995, 145000]),
 array(['Automatic', 'Manual', 'Semi-Auto'], dtype=object),
 array([     1,      5,      7, ..., 152034, 168017, 323000]),
 array(['Diesel', 'Hybrid', 'Petrol'], dtype=object),
 array([  0,  20,  30, 115, 125, 135, 140, 145, 150, 155, 160, 165, 190,
        195, 200, 205, 220, 230, 235, 240, 260, 265, 280, 290, 295, 300,
        305, 315, 325, 330, 515, 535, 540, 555, 565, 570, 580]),
 array([ 18.9,  19.3,  19.6,  20.3,  21. ,  21.1,  21.4,  21.6,  21.9,
         22.1,  22.4,  22.6,  22.8,  23. ,  24.1,  24.8,  25. ,  26.4,
         26.9,  27.2,  27.4

In [15]:
df_encoder=encoder.fit_transform(df).toarray()

In [16]:
df_encoder

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [17]:
df_encoder.shape

(10668, 11198)

In [18]:
df_dummy=pd.get_dummies(df)

In [19]:
df_dummy

year  price  mileage  tax   mpg  engineSize  model_ A1  model_ A2  \
0      2017  12500    15735  150  55.4         1.4          1          0   
1      2016  16500    36203   20  64.2         2.0          0          0   
2      2016  11000    29946   30  55.4         1.4          1          0   
3      2017  16800    25952  145  67.3         2.0          0          0   
4      2019  17300     1998  145  49.6         1.0          0          0   
...     ...    ...      ...  ...   ...         ...        ...        ...   
10663  2020  16999     4018  145  49.6         1.0          0          0   
10664  2020  16999     1978  150  49.6         1.0          0          0   
10665  2020  17199      609  150  49.6         1.0          0          0   
10666  2017  19499     8646  150  47.9         1.4          0          0   
10667  2016  15999    11855  150  47.9         1.4          0          0   

       model_ A3  model_ A4  ...  model_ S8  model_ SQ5  model_ SQ7  \
0              0          0  ...          0           0           0   
1              0          0  ...          0           0           0   
2              0          0  ...          0           0           0   
3              0          1  ...          0           0           0   
4              1          0  ...          0           0           0   
...          ...        ...  ...        ...         ...         ...   
10663          1          0  ...          0           0           0   
10664          1          0  ...          0           0           0   
10665          1          0  ...          0           0           0   
10666          0          0  ...          0           0           0   
10667          0          0  ...          0           0           0   

       model_ TT  transmission_Automatic  transmission_Manual  \
0              0                       0                    1   
1              0                       1                    0   
2              0                       0                    1   
3              0                       1                    0   
4              0                       0                    1   
...          ...                     ...                  ...   
10663          0                       0                    1   
10664          0                       0                    1   
10665          0                       0                    1   
10666          0                       1                    0   
10667          0                       0                    1   

       transmission_Semi-Auto  fuelType_Diesel  fuelType_Hybrid  \
0                           0                0                0   
1                           0                1                0   
2                           0                0                0   
3                           0                1                0   
4                           0                0                0   
...                       ...              ...              ...   
10663                       0                0                0   
10664                       0                0                0   
10665                       0                0                0   
10666                       0                0                0   
10667                       0                0                0   

       fuelType_Petrol  
0                    1  
1                    0  
2                    1  
3                    0  
4                    1  
...                ...  
10663                1  
10664                1  
10665                1  
10666                1  
10667                1  

[10668 rows x 38 columns]

In [20]:
df_dummy.columns

Index(['year', 'price', 'mileage', 'tax', 'mpg', 'engineSize', 'model_ A1',
       'model_ A2', 'model_ A3', 'model_ A4', 'model_ A5', 'model_ A6',
       'model_ A7', 'model_ A8', 'model_ Q2', 'model_ Q3', 'model_ Q5',
       'model_ Q7', 'model_ Q8', 'model_ R8', 'model_ RS3', 'model_ RS4',
       'model_ RS5', 'model_ RS6', 'model_ RS7', 'model_ S3', 'model_ S4',
       'model_ S5', 'model_ S8', 'model_ SQ5', 'model_ SQ7', 'model_ TT',
       'transmission_Automatic', 'transmission_Manual',
       'transmission_Semi-Auto', 'fuelType_Diesel', 'fuelType_Hybrid',
       'fuelType_Petrol'],
      dtype='object')

In [21]:
df_dummy.shape

(10668, 38)

In [22]:
import matplotlib.pyplot as plt


In [23]:
df_dummy.price

0        12500
1        16500
2        11000
3        16800
4        17300
         ...  
10663    16999
10664    16999
10665    17199
10666    19499
10667    15999
Name: price, Length: 10668, dtype: int64

In [24]:
X=df_dummy.drop('price',axis=1)
Y=df_dummy.price

In [27]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [29]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [30]:
from sklearn.decomposition import PCA

prcoan = PCA(n_components = 2)

X_train = prcoan.fit_transform(X_train)
X_test = prcoan.transform(X_test)

explained_variance = prcoan.explained_variance_ratio_

In [32]:
total_variance = prcoan.explained_variance_ratio_.sum() * 100

In [33]:
total_variance

17.186281998584167

In [34]:
labels = {str(i): f"PC {i+1}" for i in range(2)}

In [37]:
import plotly.express as px
fig = px.scatter_matrix(
    X_train,

    dimensions=range(2),
    labels=labels,
    title=f'Tot Explained Variance: {total_variance:.2f}%',
)
fig.update_traces(diagonal_visible=False)
fig.show()